name: Esegui Script

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: 'Parola chiave per la ricerca'
        required: false
        default: 'samples'

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Setup di Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installazione dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esecuzione script principale
        run: |
          python main.py --keyword "${{ github.event.inputs.keyword }}"

      - name: Caricamento samples come artifact
        uses: actions/upload-artifact@v3
        with:
          name: samples
          path: downloads/
          retention-days: 1
